<a href="https://colab.research.google.com/github/saniya8858/ML_LAB_49/blob/main/LAB1_49_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install picatrix

  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.4/76.4 kB 1.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.1/70.1 kB 4.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Using cached jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.4/147.4 kB 1.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/9.4 MB 16.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 16.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.2/190.2 kB 10.9 MB/s eta 0:00:00
Using cached jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.9/137.9 kB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 18.9 MB/s 

In [2]:
import numpy as np
import pandas as pd

In [4]:
pd

<module 'pandas' from '/usr/local/lib/python3.10/dist-packages/pandas/__init__.py'>

In [5]:
!ls ~/ && pwd

/content


In [6]:
pd.read_csv?

In [7]:
pd.read_*?

In [8]:
%magic

In [9]:
%%timeit
for index in range(0, 10):
  _ = index * 10

578 ns ± 8.03 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
output = %pwd

In [11]:
output

'/content'

In [12]:
from picatrix import notebook_init

notebook_init.init()

In [13]:
%picatrixmagics

name  \
2                        last_output   
0                    picatrixhelpers   
1                     picatrixmagics   
5        timesketch_add_manual_event   
18  timesketch_available_aggregators   
9            timesketch_context_date   
10            timesketch_context_row   
12          timesketch_create_sketch   
27   timesketch_events_with_comments   
17       timesketch_get_aggregations   
4              timesketch_get_client   
13     timesketch_get_saved_searches   
24      timesketch_get_searchindices   
3              timesketch_get_sketch   
23           timesketch_get_sketches   
26     timesketch_get_starred_events   
11          timesketch_get_timelines   
19       timesketch_get_token_status   
7     timesketch_list_saved_searches   
28           timesketch_list_stories   
16         timesketch_list_timelines   
8                   timesketch_query   
20          timesketch_refresh_token   
21    timesketch_run_aggregation_dsl   
22         timesketch_run_aggregator   
25        timesketch_search_by_label   
14      timesketch_set_active_sketch   
15            timesketch_upload_data   
6             timesketch_upload_file   

                                          description  \
2                usage: %last_output [arguments] data   
0            usage: %picatrixhelpers [arguments] data   
1             usage: %picatrixmagics [arguments] data   
5   usage: %timesketch_add_manual_event [arguments...   
18  usage: %timesketch_available_aggregators [argu...   
9    usage: %timesketch_context_date [arguments] data   
10    usage: %timesketch_context_row [arguments] data   
12  usage: %timesketch_create_sketch [arguments] data   
27  usage: %timesketch_events_with_comments [argum...   
17  usage: %timesketch_get_aggregations [arguments...   
4      usage: %timesketch_get_client [arguments] data   
13  usage: %timesketch_get_saved_searches [argumen...   
24  usage: %timesketch_get_searchindices [argument...   
3      usage: %timesketch_get_sketch [arguments] data   
23   usage: %timesketch_get_sketches [arguments] data   
26  usage: %timesketch_get_starred_events [argumen...   
11  usage: %timesketch_get_timelines [arguments] data   
19  usage: %timesketch_get_token_status [arguments...   
7   usage: %timesketch_list_saved_searches [argume...   
28   usage: %timesketch_list_stories [arguments] data   
16  usage: %timesketch_list_timelines [arguments] ...   
8           usage: %timesketch_query [arguments] data   
20  usage: %timesketch_refresh_token [arguments] data   
21  usage: %timesketch_run_aggregation_dsl [argume...   
22  usage: %timesketch_run_aggregator [arguments] ...   
25  usage: %timesketch_search_by_label [arguments]...   
14  usage: %timesketch_set_active_sketch [argument...   
15    usage: %timesketch_upload_data [arguments] data   
6     usage: %timesketch_upload_file [arguments] data   

                                 line                                cell  \
2                        %last_output                       %%last_output   
0                    %picatrixhelpers                   %%picatrixhelpers   
1                     %picatrixmagics                    %%picatrixmagics   
5        %timesketch_add_manual_event       %%timesketch_add_manual_event   
18  %timesketch_available_aggregators  %%timesketch_available_aggregators   
9            %timesketch_context_date           %%timesketch_context_date   
10            %timesketch_context_row            %%timesketch_context_row   
12          %timesketch_create_sketch          %%timesketch_create_sketch   
27   %timesketch_events_with_comments   %%timesketch_events_with_comments   
17       %timesketch_get_aggregations       %%timesketch_get_aggregations   
4              %timesketch_get_client             %%timesketch_get_client   
13     %timesketch_get_saved_searches     %%timesketch_get_saved_searches   
24      %timesketch_get_searchindices      %%timesketch_get_searchindices   
3              %timesketch_get_sketch     

In [14]:
%picatrixmagics --help

usage: %picatrixmagics [arguments] data
or
%%picatrixmagics [arguments]
data

Provides information about registered Picatrix magics.

positional arguments:
  data                  If empty an overview of all registered magics is provided, otherwise the
                        help message of a particular magic is provided.

options:
  -h, --help            show this help message and exit
  --bindto BINDTO, -bindto BINDTO
                        Bind the results to a variable instead of being returned.


In [15]:
arr = np.arange(10000)

In [16]:
arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
print(len(arr))

10000


In [18]:
arr_list = list(range(10000))
print(len(arr_list))

10000


In [19]:
%time a = [x * 10 for x in arr_list]

CPU times: user 1.27 ms, sys: 22 µs, total: 1.29 ms
Wall time: 1.3 ms


In [20]:
arr = np.random.randn(4, 4)

In [21]:
arr

array([[ 2.28497886,  1.22975593,  0.752255  , -1.05661799],
       [-0.8587945 ,  2.34825988, -0.15936056,  0.25681124],
       [-1.3336329 , -0.25788749, -0.52133663, -0.65361092],
       [-0.58052805,  0.94220847,  1.67109731,  1.15401081]])

In [22]:
arr * 3

array([[ 6.85493657,  3.68926779,  2.25676501, -3.16985396],
       [-2.57638349,  7.04477964, -0.47808167,  0.77043373],
       [-4.00089871, -0.77366246, -1.56400988, -1.96083275],
       [-1.74158414,  2.82662541,  5.01329193,  3.46203243]])

In [23]:
arr + arr

array([[ 4.56995771,  2.45951186,  1.50451   , -2.11323597],
       [-1.71758899,  4.69651976, -0.31872111,  0.51362248],
       [-2.66726581, -0.51577497, -1.04267325, -1.30722183],
       [-1.16105609,  1.88441694,  3.34219462,  2.30802162]])

In [24]:
arr[0, 2]

0.7522550019718209

In [25]:
arr[0:2]

array([[ 2.28497886,  1.22975593,  0.752255  , -1.05661799],
       [-0.8587945 ,  2.34825988, -0.15936056,  0.25681124]])

In [26]:
arr[0:2, 1:3]

array([[ 1.22975593,  0.752255  ],
       [ 2.34825988, -0.15936056]])

In [27]:
arr = np.array(['time', 'picatrix', 'sketch', 'magic', 'wizard'])

In [28]:
arr

array(['time', 'picatrix', 'sketch', 'magic', 'wizard'], dtype='<U8')

In [29]:
arr == 'time'

array([ True, False, False, False, False])

In [30]:
arr[arr == 'time']

array(['time'], dtype='<U8')

In [31]:
pd.Series(['a', 'b', 'c', 'd', 'e'])

0    a
1    b
2    c
3    d
4    e
dtype: object

In [32]:
ser = pd.Series(['a', 'b', 'c', 'd', 'e'], index=['foo', 'bar', 'more', 'note', 'extra'])

In [33]:
ser

foo      a
bar      b
more     c
note     d
extra    e
dtype: object

In [34]:
ser.foo

'a'

In [35]:
ser['foo']

'a'

In [36]:
ser.to_dict()

{'foo': 'a', 'bar': 'b', 'more': 'c', 'note': 'd', 'extra': 'e'}

In [37]:
ser = pd.Series({
    'stuff': 134,
    'more': 11,
    'notes': 'extra stuff'
})

In [38]:
ser

stuff            134
more              11
notes    extra stuff
dtype: object

In [39]:
ser.notes

'extra stuff'

In [40]:
ser.str.contains('stuff')

stuff     NaN
more      NaN
notes    True
dtype: object

In [41]:
ser.str.extract(r' (s[^ $]+)')

0
stuff    NaN
more     NaN
notes  stuff

In [42]:
lines = [
    {'Important': True, 'Value': 1345, 'Notes': 'Stuff IS Stuff'},
    {'Important': True, 'Value': 23, 'Notes': 'This does not contain any word...'},
    {'Important': True, 'Value': 523, 'Notes': 'We have a lot of text in here, including stuff'},
    {'Important': False, 'Value': 100, 'Notes': 'Here is a word that sounds like stuff but is in fact soooo much longer'},
]

df = pd.DataFrame(lines)

In [43]:
df

Important  Value                                              Notes
0       True   1345                                     Stuff IS Stuff
1       True     23                  This does not contain any word...
2       True    523     We have a lot of text in here, including stuff
3      False    100  Here is a word that sounds like stuff but is i...

In [44]:
df.shape

(4, 3)

In [45]:
df.head(2)

Important  Value                              Notes
0       True   1345                     Stuff IS Stuff
1       True     23  This does not contain any word...

In [46]:
df.tail(2)

Important  Value                                              Notes
2       True    523     We have a lot of text in here, including stuff
3      False    100  Here is a word that sounds like stuff but is i...

In [47]:
df['Value']

0    1345
1      23
2     523
3     100
Name: Value, dtype: int64

In [48]:
df['Notes'].str.contains('stuff')

0    False
1    False
2     True
3     True
Name: Notes, dtype: bool

In [49]:
df[df['Notes'].str.contains('stuff')]

Important  Value                                              Notes
2       True    523     We have a lot of text in here, including stuff
3      False    100  Here is a word that sounds like stuff but is i...

In [50]:
df[df['Important']]

Important  Value                                           Notes
0       True   1345                                  Stuff IS Stuff
1       True     23               This does not contain any word...
2       True    523  We have a lot of text in here, including stuff

In [51]:
df['NewValue'] = 5452

In [52]:
df

Important  Value                                              Notes  \
0       True   1345                                     Stuff IS Stuff   
1       True     23                  This does not contain any word...   
2       True    523     We have a lot of text in here, including stuff   
3      False    100  Here is a word that sounds like stuff but is i...   

   NewValue  
0      5452  
1      5452  
2      5452  
3      5452

In [53]:
df['stuff'] = df['Notes'].str.extract(r'\b([sS][^ $]+)')

In [54]:
df

Important  Value                                              Notes  \
0       True   1345                                     Stuff IS Stuff   
1       True     23                  This does not contain any word...   
2       True    523     We have a lot of text in here, including stuff   
3      False    100  Here is a word that sounds like stuff but is i...   

   NewValue   stuff  
0      5452   Stuff  
1      5452     NaN  
2      5452   stuff  
3      5452  sounds

In [55]:
df['Important'].value_counts()

Important
True     3
False    1
Name: count, dtype: int64

In [56]:
df['Important'].unique()

array([ True, False])

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Important  4 non-null      bool  
 1   Value      4 non-null      int64 
 2   Notes      4 non-null      object
 3   NewValue   4 non-null      int64 
 4   stuff      3 non-null      object
dtypes: bool(1), int64(2), object(2)
memory usage: 260.0+ bytes


In [58]:
df.describe()

Value  NewValue
count     4.000000       4.0
mean    497.750000    5452.0
std     606.097558       0.0
min      23.000000    5452.0
25%      80.750000    5452.0
50%     311.500000    5452.0
75%     728.500000    5452.0
max    1345.000000    5452.0

In [59]:
df[df['Important']]

Important  Value                                           Notes  NewValue  \
0       True   1345                                  Stuff IS Stuff      5452   
1       True     23               This does not contain any word...      5452   
2       True    523  We have a lot of text in here, including stuff      5452   

   stuff  
0  Stuff  
1    NaN  
2  stuff

In [60]:
df[(df['Important']) & (df['Notes'].str.contains('stuff', case=False))]

Important  Value                                           Notes  NewValue  \
0       True   1345                                  Stuff IS Stuff      5452   
2       True    523  We have a lot of text in here, including stuff      5452   

   stuff  
0  Stuff  
2  stuff

In [61]:
df_slice = df[(df['Important']) & (df['Notes'].str.contains('stuff', case=False))]

df_slice[df_slice.Value > 1000]

Important  Value           Notes  NewValue  stuff
0       True   1345  Stuff IS Stuff      5452  Stuff

In [62]:
df.iloc[0]

Important              True
Value                  1345
Notes        Stuff IS Stuff
NewValue               5452
stuff                 Stuff
Name: 0, dtype: object

In [63]:
df.iloc[0:2]

Important  Value                              Notes  NewValue  stuff
0       True   1345                     Stuff IS Stuff      5452  Stuff
1       True     23  This does not contain any word...      5452    NaN

In [64]:
df.loc[2]

Important                                              True
Value                                                   523
Notes        We have a lot of text in here, including stuff
NewValue                                               5452
stuff                                                 stuff
Name: 2, dtype: object

In [65]:
df.loc[2:3, 'Value']

2    523
3    100
Name: Value, dtype: int64

In [66]:
df['NewIndex'] = pd.Series(['A', 'B', 'C', 'D'])
df.set_index('NewIndex', inplace=True)

In [67]:
df

Important  Value                                              Notes  \
NewIndex                                                                        
A              True   1345                                     Stuff IS Stuff   
B              True     23                  This does not contain any word...   
C              True    523     We have a lot of text in here, including stuff   
D             False    100  Here is a word that sounds like stuff but is i...   

          NewValue   stuff  
NewIndex                    
A             5452   Stuff  
B             5452     NaN  
C             5452   stuff  
D             5452  sounds

In [68]:
df.loc['B']

Important                                 True
Value                                       23
Notes        This does not contain any word...
NewValue                                  5452
stuff                                      NaN
Name: B, dtype: object

In [69]:
df.loc['B':'D']

Important  Value                                              Notes  \
NewIndex                                                                        
B              True     23                  This does not contain any word...   
C              True    523     We have a lot of text in here, including stuff   
D             False    100  Here is a word that sounds like stuff but is i...   

          NewValue   stuff  
NewIndex                    
B             5452     NaN  
C             5452   stuff  
D             5452  sounds

In [70]:
df.sort_values('Value')

Important  Value                                              Notes  \
NewIndex                                                                        
B              True     23                  This does not contain any word...   
D             False    100  Here is a word that sounds like stuff but is i...   
C              True    523     We have a lot of text in here, including stuff   
A              True   1345                                     Stuff IS Stuff   

          NewValue   stuff  
NewIndex                    
B             5452     NaN  
D             5452  sounds  
C             5452   stuff  
A             5452   Stuff

In [71]:
df.sort_values('Value', ascending=False)

Important  Value                                              Notes  \
NewIndex                                                                        
A              True   1345                                     Stuff IS Stuff   
C              True    523     We have a lot of text in here, including stuff   
D             False    100  Here is a word that sounds like stuff but is i...   
B              True     23                  This does not contain any word...   

          NewValue   stuff  
NewIndex                    
A             5452   Stuff  
C             5452   stuff  
D             5452  sounds  
B             5452     NaN

In [72]:
df.rank()

Important  Value  Notes  NewValue  stuff
NewIndex                                          
A               3.0    4.0    2.0       2.5    1.0
B               3.0    1.0    3.0       2.5    NaN
C               3.0    3.0    4.0       2.5    3.0
D               1.0    2.0    1.0       2.5    2.0

In [73]:
df.rank(axis='columns')

TypeError: '<' not supported between instances of 'int' and 'str'

In [74]:
df.Value.sum()

1991

In [75]:
df.Value.mean()

497.75

In [76]:
df.Value.cumsum()

NewIndex
A    1345
B    1368
C    1891
D    1991
Name: Value, dtype: int64

In [77]:
pd.read_*?

In [78]:
import csv

with open('/tmp/foobar.csv', 'w') as fw:
  writer = csv.writer(fw)
  writer.writerow(['First', 'Second', 'Third'])
  writer.writerow([1, 2, 4])
  writer.writerow([5, 3, 2])
  writer.writerow([1, 3, 0])

In [79]:
df = pd.read_csv('/tmp/foobar.csv')

In [80]:
df

First  Second  Third
0      1       2      4
1      5       3      2
2      1       3      0

In [81]:
for chunk in pd.read_csv('/tmp/foobar.csv', chunksize=2):
  print(chunk.shape)

(2, 3)
(1, 3)
